// 22.06.2012 :: zombie 

using System;
using System.Collections;
using Server.Mobiles;
using Server.Factions;

namespace Server
{
	public class SpeedInfo
	{
		// Should we use the new method of speeds?
		private static bool Enabled = true;

		// 24.09.2013 :: mortuus - zwiekszenie predkosci wszystkich stworzen
		private static double globalSpeedFactor = 1.65;

		private double m_ActiveSpeed;
		private double m_PassiveSpeed;
		private Type[] m_Types;

		public double ActiveSpeed
		{
			get{ return m_ActiveSpeed; }
			set{ m_ActiveSpeed = value; }
		}

		public double PassiveSpeed
		{
			get{ return m_PassiveSpeed; }
			set{ m_PassiveSpeed = value; }
		}

		public Type[] Types
		{
			get{ return m_Types; }
			set{ m_Types = value; }
		}

		public SpeedInfo( double activeSpeed, double passiveSpeed, Type[] types )
		{
			m_ActiveSpeed = activeSpeed * globalSpeedFactor;
			m_PassiveSpeed = passiveSpeed * globalSpeedFactor;
			m_Types = types;
		}

		public static bool Contains( object obj )
		{
			if ( !Enabled )
				return false;

			if ( m_Table == null )
				LoadTable();

			SpeedInfo sp = (SpeedInfo)m_Table[obj.GetType()];

			return ( sp != null );
		}

		public static bool GetSpeeds( object obj, ref double activeSpeed, ref double passiveSpeed )
		{
			if ( !Enabled )
				return false;

			if ( m_Table == null )
				LoadTable();

			SpeedInfo sp = (SpeedInfo)m_Table[obj.GetType()];

			if ( sp == null )
				return false;

			activeSpeed = sp.ActiveSpeed;
			passiveSpeed = sp.PassiveSpeed;

			return true;
		}

		private static void LoadTable()
		{
			m_Table = new Hashtable();

			for ( int i = 0; i < m_Speeds.Length; ++i )
			{
				SpeedInfo info = m_Speeds[i];
				Type[] types = info.Types;

                for ( int j = 0; j < types.Length; ++j )
                {
                    if(m_Table.ContainsKey( types[ j ] ) )
                        Console.WriteLine( "Powtorzenie w SpeedInfo.cs: " + types[ j ] );
                    else
                        m_Table[ types[ j ] ] = info;
                }
			}
		}

		private static Hashtable m_Table;

        // posortowane alfabetycznie
		private static SpeedInfo[] m_Speeds = new SpeedInfo[]
			{
                /* Veeeeery Slooooow */
				new SpeedInfo( 0.55, 1.0, new Type[]
				{
					typeof( Aminia ),
					typeof( ChaosGuard ),
					typeof( Mummy2 ),
					typeof( Mummy3 ),
					typeof( OrderGuard ),
					typeof( Tangle ),
					typeof( UnfrozenMummy ),
					typeof( XmlQuestNPC )
				} ),
                /* Very Slow */
				new SpeedInfo( 0.3, 0.6, new Type[]
				{
                    typeof( Boar ),
                    typeof( BogThing ),
                    typeof( FrostOoze ),
                    typeof( FrostTroll ),
                    typeof( GazerLarva ),
                    typeof( Ghoul ),
                    typeof( HeadlessOne ),
                    typeof( Juggernaut ),
                    typeof( Jwilson ),
                    typeof( MoundOfMaggots ),
                    typeof( PlagueBeast ),
                    typeof( Quagmire ),
                    typeof( RestlessSoul ),
                    typeof( RottingCorpse ),
                    typeof( ShadowWisp ),
                    typeof( Skeleton ),
                    typeof( Slime ),
                    typeof( Walrus ),
                    typeof( Zombie )
				} ),
				/* Slow */
				new SpeedInfo( 0.25, 0.5, new Type[]
				{
                    typeof( AntLion ),
                    typeof( xCommonArcaneDaemon ),
                    typeof( ArcticOgreLord ),
                    typeof( BlackSolenWorker ),
                    typeof( BloodElemental ),
                    typeof( Bogle ),
                    typeof( BoneKnight ),
                    typeof( BoneMagi ),
                    typeof( Brigand ),
                    typeof( BullFrog ),
                    typeof( Cat ),
                    typeof( Chicken ),
                    typeof( Cow ),
                    typeof( CrystalElemental ),
                    typeof( Cyclops ),
                    typeof( DarknightCreeper ),
                    typeof( EarthElemental ),
                    typeof( ElderGazer ),
                    typeof( EnslavedGargoyle ),
                    typeof( Ettin ),
                    typeof( FleshGolem ),
                    typeof( Gazer ),
                    typeof( GiantSpider ),
                    typeof( Gibberling ),
                    typeof( Golem ),
                    typeof( GolemController ),
					typeof( GreaterDragon ),
					typeof( feniks ),
                    typeof( LesserHordeDaemon ),
                    typeof( IceElemental ),
                    typeof( JukaLord ),
                    typeof( JukaMage ),
                    typeof( LichLord ),
                    typeof( Lizardman ),
                    typeof( Mongbat ),
                    typeof( Mummy ),
                    typeof( NDeloth ),
                    typeof( NDzahhar ),
					typeof( NKatrill ),
                    typeof( NBurugh ),
                    typeof( NelderimSkeletalDragon ),
                    typeof( NGorogon ),
                    typeof( NSilshashaszals ),
                    typeof( NStarozytnyLodowySmok ),
                    typeof( NStarozytnySmok ),
                    typeof( NSzeol ),
                    typeof( WladcaDemonow ),
                    typeof( Zhoaminth ),
                    typeof( Ogre ),
                    typeof( OgreLord ),
                    typeof( Orc ),
                    typeof( OrcBomber ),
                    typeof( OrcishMage ),
                    typeof( PatchworkSkeleton ),
                    typeof( Pig ),
                    typeof( Rat ),
                    typeof( Ratman ),
                    typeof( RatmanMage ),
                    typeof( RedSolenWorker ),
                    typeof( Serado ),
                    typeof( Sewerrat ),
                    typeof( Sheep ),
                    typeof( SkitteringHopper ),
                    typeof( StrongMongbat ),
                    typeof( SummonedDaemon ),
                    typeof( SummonedEarthElemental ),
                    typeof( SummonedFireElemental ),
                    typeof( SummonedWaterElemental ),
                    typeof( SwampTentacle ),
                    typeof( TerathanDrone ),
                    typeof( Titan ),
                    typeof( Treefellow ),
                    typeof( Troll ),
                    typeof( WhippingVine )
				} ),
                /* Medium */
				new SpeedInfo( 0.2, 0.4, new Type[]
				{
                    typeof( Abscess ),
                    typeof( Actor ),
                    typeof( AgapiteElemental ),
                    typeof( AlbinoSquirrel ),
                    typeof( Alligator ),
					typeof ( AmethystDragon ),
					typeof ( AmethystDrake ),
					typeof ( DiamondDragon ),
					typeof ( DiamondDrake ),
					typeof ( EmeraldDragon ),
					typeof ( EmeraldDrake ),
					typeof ( RubyDragon ),
					typeof ( RubyDrake ),
					typeof ( SapphireDragon ),
					typeof ( SapphireDrake ),
                    typeof( AncientLich ),
                    typeof( AncientSeaMonster ),
                    typeof( Arachne ),
                    typeof( ArcaneFey ),
                    typeof( ArcaneFiend ),
                    typeof( ArcherNelderimGuard ),
                    typeof( AReaperRedux ),
                    typeof( Artist ),
					typeof ( BagiennaLama ),
                    typeof( BakeKitsune ),
                    typeof( BaseEscortable ),
                    typeof( Betrayer ),
                    typeof( Bird ),
                    typeof( BlackBear ),
                    typeof( BlackSolenInfiltratorWarrior ),
                    typeof( BlackSolenWarrior ),
                    typeof( BladeSpirits ),
                    typeof( Bogling ),
                    typeof( BrideGroom ),
                    typeof( BronzeElemental ),
                    typeof( BrownBear ),
                    typeof( BulbousPutrification ),
                    typeof( Bull ),
                    typeof( CapturedHordeMinion ),
                    typeof( Centaur ),
                    typeof( xCommonChaosDaemon ),
                    typeof( ChiefParoxysmus ),
                    typeof( ChiefParoxysmusAvatar ),
                    typeof( Chiikkaha ),
                    typeof( CopperElemental ),
                    typeof( CorporealBrume ),
                    typeof( Corpser ),
					typeof( Corpser2 ),
                    typeof( CorrosiveSlime ),
                    typeof( Crane ),
                    typeof( CrystalDaemon ),
                    typeof( CrystalHydra ),
                    typeof( CrystalLatticeSeeker ),
                    typeof( CrystalSeaSerpent ),
                    typeof( CrystalVortex ),
                    typeof( CrystalWisp ),
                    typeof( Cursed ),
                    typeof( CuSidhe ),
                    typeof( CommonDaemon ),
                    typeof( DarkWisp ),
                    typeof( DarkWolfFamiliar ),
                    typeof( DeathAdder ),
                    typeof( DeathSpiderFamiliar ),
                    typeof( DeathwatchBeetle ),
                    typeof( DeathwatchBeetleHatchling ),
                    typeof( DeepSeaSerpent ),
                    typeof( DemonicznySluga ),
                    typeof( DesertOstard ),
                    typeof( Devourer ),
                    typeof( Dog ),
                    typeof( Dolphin ),
                    typeof( Doppleganger ),
                    typeof( Dragon ),
                    typeof( DragonsFlameGrandMage ),
                    typeof( DragonsFlameMage ),
                    typeof( Drake ),
                    typeof( DreadHorn ),
                    typeof( DullCopperElemental ),
                    typeof( DummyAssassin ),
                    typeof( DummyFence ),
                    typeof( DummyHealer ),
                    typeof( DummyMace ),
                    typeof( DummyNox ),
                    typeof( DummyStun ),
                    typeof( DummySuper ),
                    typeof( DummySword ),
                    typeof( DummyTheif ),
                    typeof( ElfBrigand ),
                    typeof( EnslavedSatyr ),
                    typeof( EscortableMage ),
                    typeof( EttinLord ),
                    typeof( EvilHealer ),
                    typeof( EvilMage ),
                    typeof( EvilMageLord ),
                    typeof( EvilWanderingHealer ),
                    typeof( Executioner ),
                    typeof( ExodusOverseer ),
                    typeof( FerelTreefellow ),
                    typeof( Ferret ),
                    typeof( FetidEssence ),
                    typeof( FieryGoblinSapper ),
                    typeof( FireBeetle ),
                    typeof( FireGargoyle ),
                    typeof( Flurry ),
                    typeof( FrostSpider ),
                    typeof( Gaman ),
                    typeof( Gargoyle ),
                    typeof( GargoyleEnforcer ),
                    typeof( GiantIceWorm ),
                    typeof( GiantRat ),
                    typeof( GiantSerpent ),
                    typeof( GiantToad ),
                    typeof( Gnaw ),
                    typeof( Goat ),
					typeof ( GorskiWilk ),
                    typeof( Goblin ),
                    typeof( GoblinSapper ),
                    typeof( GoblinWarrior ),
                    typeof( GoldenElemental ),
                    typeof( GoreFiend ),
                    typeof( Gorilla ),
                    typeof( Gregorio ),
                    typeof( Grim ),
                    typeof( GrimmochDrummel ),
                    typeof( Grobu ),
                    typeof( Guardian ),
                    typeof( Gypsy ),
                    typeof( HarborMaster ),
                    typeof( Harpy ),
                    typeof( Harrower ),
                    typeof( HarrowerTentacles ),
                    typeof( HellHorse ),
                    typeof( HellHound ),
                    typeof( Hind ),
                    typeof( HolyFamiliar ),
                    typeof( CommonHordeDaemon ),
                    typeof( HordeMinionFamiliar ),
                    typeof( HumanBrigand ),
                    typeof( Hydra ),
                    typeof( IceFiend ),
                    typeof( IceSerpent ),
                    typeof( Imp ),
                    typeof( Impaler ),
                    typeof( InsaneDryad ),
                    typeof( InterredGrizzle ),
                    typeof( JackRabbit ),
                    typeof( JukaWarrior ),
                    typeof( Kappa ),
					typeof ( KamiennaWyverna ),
                    typeof( KazeKemono ),
                    typeof( KhaldunSummoner ),
                    typeof( KhaldunZealot ),
                    typeof( Kraken ),
                    typeof( KusznikMorrlok ),
                    typeof( LadyLissith ),
                    typeof( LadyMelisande ),
                    typeof( LadySabrix ),
                    typeof( LavaLizard ),
                    typeof( LavaSerpent ),
                    typeof( LesserArcaneDaemon ),
                    typeof( LesserChaosDaemon ),
                    typeof( LesserDaemon ),
                    typeof( LesserGoblinSapper ),
                    typeof( LesserMoloch ),
                    typeof( Llama ),
                    typeof( LodowySmok ),
                    typeof( LordMorrlok ),
                    typeof( LucznikMorrlok ),
                    typeof( Lurg ),
                    typeof( LysanderGathenwale ),
                    typeof( MagMorrlok ),
                    typeof( MantraEffervescence ),
                    typeof( MasterJonath ),
                    typeof( MasterTheophilus ),
                    typeof( MeerCaptain ),
                    typeof( MeerEternal ),
                    typeof( MeerMage ),
                    typeof( MeerWarrior ),
                    typeof( Merchant ),
                    typeof( Messenger ),
                    typeof( Mistral ),
                    typeof( MLDryad ),
                    typeof( MlodyLodowySmok ),
                    typeof( MlodyOgnistySmok ),
					typeof ( MlodyGorskiSmok ),
					typeof ( MlodaKobra ),
                    typeof( xMoloch ),
                    typeof( MonstrousInterredGrizzle ),
                    typeof( MordercaMorrlok ),
                    typeof( MorgBergen ),
                    typeof( MorrlokWarHorse ),
                    typeof( Motyl ),
                    typeof( MougGuur ),
                    typeof( MountainGoat ),
					typeof ( MrocznaCzelusc ),
                    typeof( NatureFury ),
                    typeof( NChimera ),
                    typeof( NecroMageLord ),
                    typeof( NelderimAncientLich ),
                    typeof( GreaterArcaneDaemon ),
                    typeof( GreaterChaosDaemon ),
                    typeof( GreaterDaemon ),
                    typeof( NelderimDragon ),
                    typeof( GreaterHordeDaemon ),
                    typeof( GreaterMoloch ),
                    typeof( Ninja ),
					typeof( Minotaur ),
					typeof( MinotaurBoss ),
                    typeof( MinotaurCaptain ),
                    typeof( MinotaurLord ),
                    typeof( MinotaurMage ),
					typeof( MinotaurScout ),
                    typeof( CommonMoloch ),
                    typeof( Noble ),
                    typeof( NPrzeklety ),
                    typeof( NSarag ),
                    typeof( NZapomniany ),
                    typeof( OgnistaWyverna ),
                    typeof( OgnistyNiewolnik ),
                    typeof( OgnistySmok ),
					typeof ( ogromnywilk ),
                    typeof( OgnistySzaman ),
                    typeof( OgnistyWojownik ),
                    typeof( OrcBrute ),
                    typeof( OrcCaptain ),
                    typeof( OrcishLord ),
                    typeof( OrcScout ),
                    typeof( PackLlama ),
                    typeof( PanSmierc ),
                    typeof( ParoxysmusSwampDragon ),
                    typeof( Parrot ),
                    typeof( Peasant ),
                    typeof( PestilentBandage ),
                    typeof( PetParrot ),
                    typeof( NPirateCaptain ),
                    typeof( NPirateCrew ),
                    typeof( PomiotPajaka ),
                    typeof( PrastaryLodowySmok ),
                    typeof( PrastaryOgnistySmok ),
                    typeof( PRidgeback ),
                    typeof( Protector ),
                    typeof( PSavage ),
                    typeof( PSavage1 ),
                    typeof( PSavageShaman ),
                    typeof( Putrefier ),
                    typeof( Rabbit ),
                    typeof( RagingGrizzlyBear ),
                    typeof( Reaper ),
                    typeof( RedBeetle ),
                    typeof( RedDeath ),
                    typeof( RedSolenInfiltratorWarrior ),
                    typeof( RedSolenWarrior ),
                    typeof( Rend ),
                    typeof( Reptalon ),
                    typeof( RidableLlama ),
                    typeof( Ridgeback ),
                    typeof( Saliva ),
                    typeof( Samurai ),
                    typeof( Satyr ),
                    typeof( Savage ),
                    typeof( SavageRidgeback ),
                    typeof( ScaledSwampDragon ),
                    typeof( Scorpion ),
                    typeof( Sculptor ),
                    typeof( SeaHorse ),
                    typeof( SeaSerpent ),
                    typeof( SeekerOfAdventure ),
                    typeof( SerpentsFangAssassin ),
                    typeof( SerpentsFangHighExecutioner ),
                    typeof( ServantOfSemidar ),
                    typeof( ShadowFiend ),
                    typeof( ShadowIronElemental ),
                    typeof( ShadowWispFamiliar ),
                    typeof( ShadowWyrm ),
                    typeof( ShimmeringEffusion ),
                    typeof( ShimmeringFerret ),
                    typeof( Silk ),
                    typeof( SkeletalDragon ),
                    typeof( SkeletalMount ),
					typeof ( SkalnyJaszczur ),
					typeof ( SkalnyKocur ),
					typeof ( SkalnyLew ),
					typeof ( SkalnyOgar ),
					typeof ( SkorpionKrolewski ),
                    typeof( Snake ),
					typeof ( SnieznaLama ),
					typeof ( SnowBakeKitsune ),
					typeof ( SzafirowyJednorozec ),
                    typeof( SpawnedOrcishLord ),
                    typeof( SpeckledScorpion ),
                    typeof( Sphynx ),
                    typeof( Squirrel ),
                    typeof( StaryLodowySmok ),
                    typeof( StaryOgnistySmok ),
                    typeof( StoneGargoyle ),
                    typeof( StoneHarpy ),
                    typeof( SwampDragon ),
                    typeof( Swoop ),
                    typeof( Szavetra ),
                    typeof( TalkingBaseEscortable ),
                    typeof( TalkingDrake ),
                    typeof( TalkingSeekerOfAdventure ),
                    typeof( TavaraSewel ),
                    typeof( Tempest ),
                    typeof( TerathanMatriarch ),
                    typeof( TerathanWarrior ),
                    typeof( TigersClawMaster ),
                    typeof( TigersClawThief ),
                    typeof( TormentedMinotaur ),
                    typeof( Travesty ),
                    typeof( TravestyDog ),
                    typeof( Troglodyte ),
                    typeof( TrollLord ),
                    typeof( TropicalBird ),
                    typeof( UnholyFamiliar ),
					typeof ( UpadlyJednorozec ), 
					typeof ( UpadlyKirin ),
                    typeof( ValoriteElemental ),
                    typeof( VampireBat ),
                    typeof( VampireBatFamiliar ),
                    typeof( VeriteElemental ),
                    typeof( Virulent ),
					typeof( VitVarg ),
					typeof( VitVargArcher ),
					typeof( VitVargLord ),
					typeof( VitVargMage ),
					typeof( VitVargWarrior ),
                    typeof( WailingBanshee ),
                    typeof( WandererOfTheVoid ),
                    typeof( WanderingHealer ),
                    typeof( WarHorseA ),
                    typeof( WarHorseB ),
                    typeof( WarHorseC ),
                    typeof( WarHorseD ),
                    typeof( WarHorseE ),
                    typeof( Widmak ),
                    typeof( WaterElemental ),
                    typeof( WojownikMorrlok ),
                    typeof( WolfHunter ),
                    typeof( WolfShaman ),
                    typeof( WolfWarrior ),
                    typeof( Wraith ),
                    typeof( Wyvern ),
                    typeof( YomotsuElder ),
                    typeof( YomotsuPriest ),
                    typeof( YomotsuWarrior ),
                    typeof( ZimowyOgre ),
                    typeof( ZimowyOgreLord )
			    } ),
				/* Fast */
				new SpeedInfo( 0.175, 0.35, new Type[]
				{					
                    typeof( AbysmalHorror ),
                    typeof( AirElemental ),
                    typeof( AncientWyrm ),
                    typeof( Balron ),
                    typeof( BaronowaFrozen ),
                    typeof( BlackSolenInfiltratorQueen ),
                    typeof( BlackSolenQueen ),
                    typeof( BoneDemon ),
                    typeof( CoMWarHorse ),
                    typeof( Cougar ),
                    typeof( DemonKnight ),
                    typeof( DireWolf ),
                    typeof( DreadSpider ),
                    typeof( Eagle ),
                    typeof( EnergyVortex ),
                    typeof( ExodusMinion ),
                    typeof( ExodusMinionArmored ),
                    typeof( ExodusBoss ),
                    typeof( FireElemental ),
                    typeof( FireSteed ),
                    typeof( ForestOstard ),
                    typeof( FrenziedOstard ),
                    typeof( GargoyleDestroyer ),
                    typeof( GiantBlackWidow ),
                    typeof( GreatHart ),
                    typeof( GreyWolf ),
                    typeof( GrizzlyBear ),
                    typeof( HellCat ),
                    typeof( HellSteed ),
                    typeof( Horse ),
                    typeof( JaskiniowyJaszczur ),
                    typeof( IceSnake ),
                    typeof( Kirin ),
                    typeof( LadyOfTheSnow ),
                    typeof( LavaSnake ),
                    typeof( LesserHiryu ),
					typeof ( worg ),
                    typeof( Lich ),
                    typeof( LordOaks ),
                    typeof( MinaxWarHorse ),
                    typeof( Oni ),
                    typeof( OphidianKnight ),
                    typeof( OphidianMage ),
                    typeof( OphidianWarrior ),
                    typeof( PackHorse ),
                    typeof( JaskiniowyZukJuczny ),
                    typeof( PlagueSpawn ),
                    typeof( PolarBear ),
                    typeof( RatmanArcher ),
                    typeof( Ravager ),
                    typeof( RedSolenInfiltratorQueen ),
                    typeof( RedSolenQueen ),
                    typeof( RevenantLion ),
                    typeof( Ronin ),
                    typeof( RuneBeetle ),
                    typeof( SavageRider ),
                    typeof( SavageShaman ),
                    typeof( SerpentineDragon ),
                    typeof( ShadowKnight ),
                    typeof( Silvani ),
                    typeof( SilverSteed ),
                    typeof( SLWarHorse ),
                    typeof( SnowElemental ),
                    typeof( SnowLeopard ),
					typeof ( SnieznyKirin ),
					typeof ( SnieznyRumak ),
                    typeof( SpectralArmour ),
                    typeof( StormElemental ),
                    typeof( Succubus ),
                    typeof( SummonedAirElemental ),
                    typeof( TBWarHorse ),
                    typeof( TerathanAvenger ),
                    typeof( TimberWolf ),
                    typeof( ToxicElemental ),
                    typeof( TsukiWolf ),
                    typeof( Unicorn ),
                    typeof( WhiteWolf ),
                    typeof( WhiteWyrm ),
                    typeof( Yamandon ),
					typeof ( HireBard ),
					typeof ( HireBardArcher ),
					typeof ( HireBeggar ),
					typeof ( HireFighter ),
					typeof ( HireMage ),
					typeof ( HirePaladin ),
					typeof ( HirePeasant ),
					typeof ( HireRanger ),
					typeof ( HireRangerArcher ),
					typeof ( HireSailor ),
					typeof ( HireThief ),
					
				} ),
				/* Very Fast */
				new SpeedInfo( 0.15, 0.3, new Type[]
				{
					typeof ( BagiennyKoszmar ),
                    typeof( Barracoon ),
                    typeof( Beetle ),
                    typeof( ChaosDragoon ),
                    typeof( ChaosDragoonElite ),
                    typeof( Efreet ),
                    typeof( EliteNinja ),
                    typeof( EtherealWarrior ),
                    typeof( FactionBerserker ),
                    typeof( FactionDeathKnight ),
                    typeof( FactionDragoon ),
                    typeof( FactionHenchman ),
                    typeof( FactionKnight ),
                    typeof( FactionMercenary ),
                    typeof( FactionNecromancer ),
                    typeof( FactionPaladin ),
                    typeof( FactionSorceress ),
                    typeof( FactionWizard ),
                    typeof( FanDancer ),
                    typeof( FleshRenderer ),
                    typeof( Hiryu ),
                    typeof( Leviathan ),
                    typeof( Mephitis ),
                    typeof( Neira ),
                    typeof( Nightmare ),
                    typeof( OphidianArchmage ),
                    typeof( OphidianMatriarch ),
                    typeof( Panther ),
                    typeof( PoisonElemental ),
                    typeof( PredatorHellCat ),
                    typeof( PSavageRider ),
                    typeof( RaiJu ),
                    typeof( Rikktor ),
                    typeof( SandVortex ),
                    typeof( Semidar ),
                    typeof( SilverSerpent ),
					typeof ( SkoczekZPodmroku ),
					typeof( VitVargAmazon ),
					typeof( VitVargBerserker ),
					typeof( VitVargCook ),
					typeof( VitVargCutler ),
                    typeof( Wisp )
				} ),
				/* Ultra Fast */
				new SpeedInfo( 0.1, 0.2, new Type[]
				{
                    typeof( Changeling ),
                    typeof( Coil ),
                    typeof( CorruptedSoul ),
                    typeof( Guile ),
                    typeof( Ilhenir ),
                    typeof( Irk ),
                    typeof( JezdziecMorrlok ),
                    typeof( KhaldunRevenant ),
					typeof( LadyJennifyr ),
					typeof( LadyMarai ),
					typeof( Malefic ),
					typeof( MasterMikael ),
                    typeof( Meraktus ),
					typeof( Miasma ),
                    typeof( NDuchNatury ),
                    typeof( NPoleAntymagiczne ),
                    typeof( NUpiorWalki ),
                    typeof( Phoenix ),
                    typeof( Pixie ),
					typeof( Pyre ),
					typeof( Revenant ),
					typeof( SirPatrick ),
                    typeof( Spite ),
                    typeof( StandardNelderimGuard ),
                    typeof( Thrasher ),
                    typeof( Twaulo ),
                    typeof( VorpalBunny ),
				} ),
				/* Fast and Furious */
				new SpeedInfo( 0.05, 0.1, new Type[]
				{
					typeof( MageNelderimGuard ),
					typeof( HeavyNelderimGuard ),
					typeof( MountedNelderimGuard ),
					typeof( EliteNelderimGuard ),
					typeof( SpecialNelderimGuard ),
				} ),
			};
	}
}